version: '3'

services: 
  app:
    build: ./containers/node
    volumes:
      - .:/usr/src/app
    ports:
      - '8088:8088'
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: graphql_express_sample
      MYSQL_USER: sample
      MYSQL_PASSWORD: sample
      MYSQL_ROOT_PASSWORD: password
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '4308:3306'
volumes:
  db-data:
    driver: local
